name: Sync Fork's Main Branch

on:
  schedule:
    # Runs at minute 0 past every 12th hour.
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: main # Ensure we are on the main branch

      - name: Sync fork
        run: gh repo sync danswer-ai/danswer -b main --force
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
